### ISSUE TITLE
Padronizar stylus

### ISSUE THREAD

**Issue by hansenhahn** [hansenhahn/playton-2#12]
Nos enigmas, optou-se por usar "caneta stylus"; no resto do jogo, apenas "stylus".

**Comment by ErickProductions** [comment]
Aeeee! Achei que o projeto só ia ficar pro ano que vem! Kkkk obrigado por
voltar!

Em ter, 8 de jan de 2019 às 22:13, Diego Hahn <notifications@github.com>
escreveu:

**Comment by hansenhahn** [comment]
Padronizei caneta stylus durante a história
